const eightball = ["It is certain.",
                 "It is decidedly so.",
                 "Without a doubt.",
                 "It will definitely happen.",
                 "You may rely on it.",
                 "As I see it, yes.",
                 "Most likely.",
                 "Outlook good.",
                 "100% Chance.",
                 "Signs point to yes.",
                 "Outlook hazy, try again.",
                 "Ask again later.",
                 "Cannot predict now.",
                 "Concentrate and ask again.",
                 "Don't count on it.",
                 "My reply is not likely.",
                 "My sources say no.",
                 "Outlook not good.",
                 "Very doubtful."]